<a href="https://colab.research.google.com/github/Maheshchowdary45/Activity6_Population/blob/main/GRU.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
text = """ I love to eat pizza on weekends.
She goes to the gym every morning.
The sun is shining brightly today.
We are learning natural language processing.
He forgot to bring his notebook.
My favorite color is blue.
The children are playing in the park.
I need to buy some groceries today.
They are planning a trip to Europe.
The movie was really interesting and fun.
Artificial intelligence is transforming the world.
I trained a machine learning model on this dataset.
Neural networks are inspired by the human brain.
The LSTM model is good for sequential data.
Natural language processing is a branch of AI.
What is your favorite food?
Where are you going tomorrow?
How does this algorithm work?
Can you help me with this project?
Why is deep learning so powerful?"""

In [2]:
import tensorflow as tf
from tensorflow.keras.preprocessing.text import Tokenizer

In [3]:
# initiating tokenizer

tokenizer = Tokenizer()
tokenizer.fit_on_texts([text])

In [4]:
len(tokenizer.word_index)

95

In [5]:
len(text)

760

In [6]:
for sentence in text.split("\n"):
  print(sentence)

 I love to eat pizza on weekends.
She goes to the gym every morning.
The sun is shining brightly today.
We are learning natural language processing.
He forgot to bring his notebook.
My favorite color is blue.
The children are playing in the park.
I need to buy some groceries today.
They are planning a trip to Europe.
The movie was really interesting and fun.
Artificial intelligence is transforming the world.
I trained a machine learning model on this dataset.
Neural networks are inspired by the human brain.
The LSTM model is good for sequential data.
Natural language processing is a branch of AI.
What is your favorite food?
Where are you going tomorrow?
How does this algorithm work?
Can you help me with this project?
Why is deep learning so powerful?


In [7]:
for sentence in text.split("\n"):
  print(tokenizer.texts_to_sequences([sentence])[0])

[5, 17, 3, 18, 19, 9, 20]
[21, 22, 3, 1, 23, 24, 25]
[1, 26, 2, 27, 28, 10]
[29, 4, 6, 11, 12, 13]
[30, 31, 3, 32, 33, 34]
[35, 14, 36, 2, 37]
[1, 38, 4, 39, 40, 1, 41]
[5, 42, 3, 43, 44, 45, 10]
[46, 4, 47, 7, 48, 3, 49]
[1, 50, 51, 52, 53, 54, 55]
[56, 57, 2, 58, 1, 59]
[5, 60, 7, 61, 6, 15, 9, 8, 62]
[63, 64, 4, 65, 66, 1, 67, 68]
[1, 69, 15, 2, 70, 71, 72, 73]
[11, 12, 13, 2, 7, 74, 75, 76]
[77, 2, 78, 14, 79]
[80, 4, 16, 81, 82]
[83, 84, 8, 85, 86]
[87, 16, 88, 89, 90, 8, 91]
[92, 2, 93, 6, 94, 95]


In [8]:
input_sequence = []

for sentence in text.split("\n"):
  tokenized_sentence = tokenizer.texts_to_sequences([sentence])[0]

  for i in range(1,len(tokenized_sentence)):
    input_sequence.append(tokenized_sentence[:i+1])


In [9]:
input_sequence

[[5, 17],
 [5, 17, 3],
 [5, 17, 3, 18],
 [5, 17, 3, 18, 19],
 [5, 17, 3, 18, 19, 9],
 [5, 17, 3, 18, 19, 9, 20],
 [21, 22],
 [21, 22, 3],
 [21, 22, 3, 1],
 [21, 22, 3, 1, 23],
 [21, 22, 3, 1, 23, 24],
 [21, 22, 3, 1, 23, 24, 25],
 [1, 26],
 [1, 26, 2],
 [1, 26, 2, 27],
 [1, 26, 2, 27, 28],
 [1, 26, 2, 27, 28, 10],
 [29, 4],
 [29, 4, 6],
 [29, 4, 6, 11],
 [29, 4, 6, 11, 12],
 [29, 4, 6, 11, 12, 13],
 [30, 31],
 [30, 31, 3],
 [30, 31, 3, 32],
 [30, 31, 3, 32, 33],
 [30, 31, 3, 32, 33, 34],
 [35, 14],
 [35, 14, 36],
 [35, 14, 36, 2],
 [35, 14, 36, 2, 37],
 [1, 38],
 [1, 38, 4],
 [1, 38, 4, 39],
 [1, 38, 4, 39, 40],
 [1, 38, 4, 39, 40, 1],
 [1, 38, 4, 39, 40, 1, 41],
 [5, 42],
 [5, 42, 3],
 [5, 42, 3, 43],
 [5, 42, 3, 43, 44],
 [5, 42, 3, 43, 44, 45],
 [5, 42, 3, 43, 44, 45, 10],
 [46, 4],
 [46, 4, 47],
 [46, 4, 47, 7],
 [46, 4, 47, 7, 48],
 [46, 4, 47, 7, 48, 3],
 [46, 4, 47, 7, 48, 3, 49],
 [1, 50],
 [1, 50, 51],
 [1, 50, 51, 52],
 [1, 50, 51, 52, 53],
 [1, 50, 51, 52, 53, 54],
 [1, 50, 

In [10]:
max_len = max([len(x) for x in input_sequence ])

In [11]:
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [12]:
padded_input_sequences = pad_sequences(input_sequence,maxlen = max_len,padding="pre")

In [13]:
padded_input_sequences

array([[ 0,  0,  0, ...,  0,  5, 17],
       [ 0,  0,  0, ...,  5, 17,  3],
       [ 0,  0,  0, ..., 17,  3, 18],
       ...,
       [ 0,  0,  0, ...,  2, 93,  6],
       [ 0,  0,  0, ..., 93,  6, 94],
       [ 0,  0,  0, ...,  6, 94, 95]], dtype=int32)

In [14]:
x = padded_input_sequences[:,:-1]
y = padded_input_sequences[:,-1]

In [15]:
tokenizer.word_index

{'the': 1,
 'is': 2,
 'to': 3,
 'are': 4,
 'i': 5,
 'learning': 6,
 'a': 7,
 'this': 8,
 'on': 9,
 'today': 10,
 'natural': 11,
 'language': 12,
 'processing': 13,
 'favorite': 14,
 'model': 15,
 'you': 16,
 'love': 17,
 'eat': 18,
 'pizza': 19,
 'weekends': 20,
 'she': 21,
 'goes': 22,
 'gym': 23,
 'every': 24,
 'morning': 25,
 'sun': 26,
 'shining': 27,
 'brightly': 28,
 'we': 29,
 'he': 30,
 'forgot': 31,
 'bring': 32,
 'his': 33,
 'notebook': 34,
 'my': 35,
 'color': 36,
 'blue': 37,
 'children': 38,
 'playing': 39,
 'in': 40,
 'park': 41,
 'need': 42,
 'buy': 43,
 'some': 44,
 'groceries': 45,
 'they': 46,
 'planning': 47,
 'trip': 48,
 'europe': 49,
 'movie': 50,
 'was': 51,
 'really': 52,
 'interesting': 53,
 'and': 54,
 'fun': 55,
 'artificial': 56,
 'intelligence': 57,
 'transforming': 58,
 'world': 59,
 'trained': 60,
 'machine': 61,
 'dataset': 62,
 'neural': 63,
 'networks': 64,
 'inspired': 65,
 'by': 66,
 'human': 67,
 'brain': 68,
 'lstm': 69,
 'good': 70,
 'for': 71,
 '

In [16]:
from tensorflow.keras.utils import to_categorical
y=to_categorical(y,num_classes = 96)

In [17]:
y.shape

(112, 96)

In [18]:
x.shape

(112, 8)

In [19]:
#Model Building

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding,GRU,Dense

In [21]:
num_classes = 96

# Initialize the Sequential model
model = Sequential()

# Add the Embedding layer
model.add(Embedding(input_dim=96, output_dim=100, input_length=8))

# Add the LSTM layer
model.add(GRU(150))

# Add the Dense output layer
model.add(Dense(num_classes, activation="softmax"))


/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [22]:
model.build(input_shape=(None, 8))

In [23]:
model.compile(loss="categorical_crossentropy", optimizer="adam", metrics=["accuracy"])

In [24]:
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_1 (Embedding)         │ (None, 8, 100)         │         9,600 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ gru (GRU)                       │ (None, 150)            │       113,400 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ (None, 96)             │        14,496 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 137,496 (537.09 KB)

 Trainable params: 137,496 (537.09 KB)

 Non-trainable params: 0 (0.00 B)

In [25]:
model.fit(x,y,epochs = 100)

Epoch 1/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 4s 38ms/step - accuracy: 0.0113 - loss: 4.5672
Epoch 2/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - accuracy: 0.0790 - loss: 4.5450
Epoch 3/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - accuracy: 0.1060 - loss: 4.5237
Epoch 4/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.1216 - loss: 4.4973
Epoch 5/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - accuracy: 0.0966 - loss: 4.4558
Epoch 6/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.0924 - loss: 4.3898
Epoch 7/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - accuracy: 0.0510 - loss: 4.2714
Epoch 8/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - accuracy: 0.0531 - loss: 4.2333
Epoch 9/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - accuracy: 0.0521 - loss: 4.0210
Epoch 10/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - accuracy: 0.1070 - loss: 4.0712
Epoch 11/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - accuracy: 0.1409 - loss: 4.0415
Epoch 12/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - accuracy: 0.1528 - lo

In [33]:
#Testing the model

text_2 = "They are planning a"

In [34]:
#tokenixatioin
tokenized_text_2 = tokenizer.texts_to_sequences([text_2])[0]
tokenized_text_2

[46, 4, 47, 7]

In [35]:
#Padding
padding_text_2 = pad_sequences([tokenized_text_2],maxlen = 8,padding="pre")
padding_text_2

array([[ 0,  0,  0,  0, 46,  4, 47,  7]], dtype=int32)

In [36]:
#Model
predicted_probs = model.predict(padding_text_2)
predicted_probs

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step


array([[1.44115745e-06, 7.21784425e-04, 1.04503043e-03, 3.35024064e-03,
        5.14271142e-06, 1.06973289e-06, 2.60861753e-03, 3.08628165e-04,
        1.19908203e-04, 1.17395008e-04, 5.41067834e-07, 6.40600570e-04,
        9.62923223e-04, 7.22976620e-05, 2.71110417e-04, 8.18988265e-05,
        3.49082911e-05, 8.59596403e-05, 3.36145131e-05, 7.71087143e-05,
        1.49631171e-06, 1.58717637e-06, 2.85322658e-05, 1.03075208e-05,
        1.57421368e-06, 1.24192297e-06, 1.28628917e-05, 5.86844590e-06,
        4.63815704e-05, 2.65966582e-06, 1.71646263e-06, 3.74828058e-04,
        7.33209963e-05, 1.27381383e-04, 1.21856601e-05, 1.98992598e-06,
        2.80870227e-05, 3.27931616e-06, 3.86307238e-06, 1.07701471e-05,
        5.01769828e-05, 4.66223755e-05, 3.88002518e-05, 1.81579584e-04,
        1.88854669e-04, 6.30137174e-06, 4.01067211e-07, 5.14981548e-05,
        9.64996755e-01, 1.08067696e-04, 8.67999279e-06, 1.13513643e-05,
        1.56766746e-05, 1.00091211e-05, 7.47456988e-06, 8.197906

In [37]:
import numpy as np
predicted_index = np.argmax(model.predict(padding_text_2))
predicted_index

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step


np.int64(48)

In [38]:
predicted_word = ''
for word, index in tokenizer.word_index.items():
    if index == predicted_index:
        predicted_word = word
        break

print("Next word prediction:", predicted_word)

Next word prediction: trip
