<a href="https://colab.research.google.com/github/Maheshchowdary45/Activity6_Population/blob/main/LSTM1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
text = """ I love to eat pizza on weekends.
She goes to the gym every morning.
The sun is shining brightly today.
We are learning natural language processing.
He forgot to bring his notebook.
My favorite color is blue.
The children are playing in the park.
I need to buy some groceries today.
They are planning a trip to Europe.
The movie was really interesting and fun.
Artificial intelligence is transforming the world.
I trained a machine learning model on this dataset.
Neural networks are inspired by the human brain.
The LSTM model is good for sequential data.
Natural language processing is a branch of AI.
What is your favorite food?
Where are you going tomorrow?
How does this algorithm work?
Can you help me with this project?
Why is deep learning so powerful?"""

In [2]:
import tensorflow as tf
from tensorflow.keras.preprocessing.text import Tokenizer

In [3]:
# initiating tokenizer

tokenizer = Tokenizer()
tokenizer.fit_on_texts([text])

In [4]:
len(tokenizer.word_index)

95

In [5]:
len(text)

760

In [6]:
for sentence in text.split("\n"):
  print(sentence)

 I love to eat pizza on weekends.
She goes to the gym every morning.
The sun is shining brightly today.
We are learning natural language processing.
He forgot to bring his notebook.
My favorite color is blue.
The children are playing in the park.
I need to buy some groceries today.
They are planning a trip to Europe.
The movie was really interesting and fun.
Artificial intelligence is transforming the world.
I trained a machine learning model on this dataset.
Neural networks are inspired by the human brain.
The LSTM model is good for sequential data.
Natural language processing is a branch of AI.
What is your favorite food?
Where are you going tomorrow?
How does this algorithm work?
Can you help me with this project?
Why is deep learning so powerful?


In [7]:
for sentence in text.split("\n"):
  print(tokenizer.texts_to_sequences([sentence])[0])

[5, 17, 3, 18, 19, 9, 20]
[21, 22, 3, 1, 23, 24, 25]
[1, 26, 2, 27, 28, 10]
[29, 4, 6, 11, 12, 13]
[30, 31, 3, 32, 33, 34]
[35, 14, 36, 2, 37]
[1, 38, 4, 39, 40, 1, 41]
[5, 42, 3, 43, 44, 45, 10]
[46, 4, 47, 7, 48, 3, 49]
[1, 50, 51, 52, 53, 54, 55]
[56, 57, 2, 58, 1, 59]
[5, 60, 7, 61, 6, 15, 9, 8, 62]
[63, 64, 4, 65, 66, 1, 67, 68]
[1, 69, 15, 2, 70, 71, 72, 73]
[11, 12, 13, 2, 7, 74, 75, 76]
[77, 2, 78, 14, 79]
[80, 4, 16, 81, 82]
[83, 84, 8, 85, 86]
[87, 16, 88, 89, 90, 8, 91]
[92, 2, 93, 6, 94, 95]


In [8]:
input_sequence = []

for sentence in text.split("\n"):
  tokenized_sentence = tokenizer.texts_to_sequences([sentence])[0]

  for i in range(1,len(tokenized_sentence)):
    input_sequence.append(tokenized_sentence[:i+1])


In [9]:
input_sequence

[[5, 17],
 [5, 17, 3],
 [5, 17, 3, 18],
 [5, 17, 3, 18, 19],
 [5, 17, 3, 18, 19, 9],
 [5, 17, 3, 18, 19, 9, 20],
 [21, 22],
 [21, 22, 3],
 [21, 22, 3, 1],
 [21, 22, 3, 1, 23],
 [21, 22, 3, 1, 23, 24],
 [21, 22, 3, 1, 23, 24, 25],
 [1, 26],
 [1, 26, 2],
 [1, 26, 2, 27],
 [1, 26, 2, 27, 28],
 [1, 26, 2, 27, 28, 10],
 [29, 4],
 [29, 4, 6],
 [29, 4, 6, 11],
 [29, 4, 6, 11, 12],
 [29, 4, 6, 11, 12, 13],
 [30, 31],
 [30, 31, 3],
 [30, 31, 3, 32],
 [30, 31, 3, 32, 33],
 [30, 31, 3, 32, 33, 34],
 [35, 14],
 [35, 14, 36],
 [35, 14, 36, 2],
 [35, 14, 36, 2, 37],
 [1, 38],
 [1, 38, 4],
 [1, 38, 4, 39],
 [1, 38, 4, 39, 40],
 [1, 38, 4, 39, 40, 1],
 [1, 38, 4, 39, 40, 1, 41],
 [5, 42],
 [5, 42, 3],
 [5, 42, 3, 43],
 [5, 42, 3, 43, 44],
 [5, 42, 3, 43, 44, 45],
 [5, 42, 3, 43, 44, 45, 10],
 [46, 4],
 [46, 4, 47],
 [46, 4, 47, 7],
 [46, 4, 47, 7, 48],
 [46, 4, 47, 7, 48, 3],
 [46, 4, 47, 7, 48, 3, 49],
 [1, 50],
 [1, 50, 51],
 [1, 50, 51, 52],
 [1, 50, 51, 52, 53],
 [1, 50, 51, 52, 53, 54],
 [1, 50, 

In [10]:
max_len = max([len(x) for x in input_sequence ])

In [11]:
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [12]:
padded_input_sequences = pad_sequences(input_sequence,maxlen = max_len,padding="pre")

In [13]:
padded_input_sequences

array([[ 0,  0,  0, ...,  0,  5, 17],
       [ 0,  0,  0, ...,  5, 17,  3],
       [ 0,  0,  0, ..., 17,  3, 18],
       ...,
       [ 0,  0,  0, ...,  2, 93,  6],
       [ 0,  0,  0, ..., 93,  6, 94],
       [ 0,  0,  0, ...,  6, 94, 95]], dtype=int32)

In [14]:
x = padded_input_sequences[:,:-1]
y = padded_input_sequences[:,-1]

In [15]:
tokenizer.word_index

{'the': 1,
 'is': 2,
 'to': 3,
 'are': 4,
 'i': 5,
 'learning': 6,
 'a': 7,
 'this': 8,
 'on': 9,
 'today': 10,
 'natural': 11,
 'language': 12,
 'processing': 13,
 'favorite': 14,
 'model': 15,
 'you': 16,
 'love': 17,
 'eat': 18,
 'pizza': 19,
 'weekends': 20,
 'she': 21,
 'goes': 22,
 'gym': 23,
 'every': 24,
 'morning': 25,
 'sun': 26,
 'shining': 27,
 'brightly': 28,
 'we': 29,
 'he': 30,
 'forgot': 31,
 'bring': 32,
 'his': 33,
 'notebook': 34,
 'my': 35,
 'color': 36,
 'blue': 37,
 'children': 38,
 'playing': 39,
 'in': 40,
 'park': 41,
 'need': 42,
 'buy': 43,
 'some': 44,
 'groceries': 45,
 'they': 46,
 'planning': 47,
 'trip': 48,
 'europe': 49,
 'movie': 50,
 'was': 51,
 'really': 52,
 'interesting': 53,
 'and': 54,
 'fun': 55,
 'artificial': 56,
 'intelligence': 57,
 'transforming': 58,
 'world': 59,
 'trained': 60,
 'machine': 61,
 'dataset': 62,
 'neural': 63,
 'networks': 64,
 'inspired': 65,
 'by': 66,
 'human': 67,
 'brain': 68,
 'lstm': 69,
 'good': 70,
 'for': 71,
 '

In [16]:
from tensorflow.keras.utils import to_categorical
y=to_categorical(y,num_classes = 96)

In [17]:
y.shape

(112, 96)

In [18]:
x.shape

(112, 8)

In [19]:
#Model Building

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding,LSTM,Dense

In [20]:
num_classes = 96

# Initialize the Sequential model
model = Sequential()

# Add the Embedding layer
model.add(Embedding(input_dim=96, output_dim=100, input_length=8))

# Add the LSTM layer
model.add(LSTM(150))

# Add the Dense output layer
model.add(Dense(num_classes, activation="softmax"))


/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [21]:
model.build(input_shape=(None, 8))

In [22]:
model.compile(loss="categorical_crossentropy", optimizer="adam", metrics=["accuracy"])

In [23]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ (None, 8, 100)         │         9,600 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm (LSTM)                     │ (None, 150)            │       150,600 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ (None, 96)             │        14,496 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 174,696 (682.41 KB)

 Trainable params: 174,696 (682.41 KB)

 Non-trainable params: 0 (0.00 B)

In [24]:
model.fit(x,y,epochs = 100)

Epoch 1/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 3s 27ms/step - accuracy: 0.0149 - loss: 4.5630
Epoch 2/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - accuracy: 0.0656 - loss: 4.5440
Epoch 3/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - accuracy: 0.0573 - loss: 4.5146
Epoch 4/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - accuracy: 0.0552 - loss: 4.4623
Epoch 5/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - accuracy: 0.0583 - loss: 4.3390
Epoch 6/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - accuracy: 0.0552 - loss: 4.2488
Epoch 7/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - accuracy: 0.0510 - loss: 4.2307
Epoch 8/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - accuracy: 0.0734 - loss: 4.1898
Epoch 9/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - accuracy: 0.0859 - loss: 4.1254
Epoch 10/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - accuracy: 0.0510 - loss: 4.1443
Epoch 11/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - accuracy: 0.0781 - loss: 4.0997
Epoch 12/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - accuracy: 0.0656 - lo

In [60]:
#Testing the model

text_2 = "My favorite is"

In [61]:
#tokenixatioin
tokenized_text_2 = tokenizer.texts_to_sequences([text_2])[0]
tokenized_text_2

[35, 14, 2]

In [62]:
#Padding
padding_text_2 = pad_sequences([tokenized_text_2],maxlen = 8,padding="pre")
padding_text_2

array([[ 0,  0,  0,  0,  0, 35, 14,  2]], dtype=int32)

In [63]:
#Model
predicted_probs = model.predict(padding_text_2)
predicted_probs

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step


array([[1.02384016e-04, 1.75294606e-03, 2.70799715e-02, 2.71021319e-03,
        3.45322042e-04, 6.17627447e-05, 7.48264464e-03, 3.62574449e-03,
        5.15951123e-03, 7.94137741e-05, 9.06340574e-05, 1.06752901e-04,
        2.90152908e-04, 4.14545764e-04, 1.04480803e-01, 1.16659177e-03,
        5.02673793e-04, 7.29156367e-04, 1.41691987e-03, 4.74802451e-04,
        2.45208957e-05, 4.14965616e-05, 1.46838173e-03, 1.91170286e-04,
        4.42544952e-05, 8.38057349e-06, 2.70636356e-03, 2.20244918e-02,
        2.77177338e-03, 5.40760047e-05, 5.76189705e-05, 3.60149704e-03,
        1.59427524e-02, 7.65712990e-04, 3.82730941e-04, 7.79536731e-06,
        7.64659122e-02, 3.21092695e-01, 1.75024988e-03, 4.20533150e-04,
        2.05499397e-04, 9.98688938e-06, 7.12226785e-04, 7.14914128e-03,
        5.32753766e-04, 1.54111840e-04, 3.58560210e-05, 3.86798434e-04,
        4.75928333e-04, 1.65526944e-05, 2.15338217e-03, 1.00012394e-02,
        4.91031492e-03, 1.37667300e-03, 5.06670876e-05, 1.562670

In [64]:
import numpy as np
predicted_index = np.argmax(model.predict(padding_text_2))
predicted_index

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step


np.int64(37)

In [65]:
predicted_word = ''
for word, index in tokenizer.word_index.items():
    if index == predicted_index:
        predicted_word = word
        break

print("Next word prediction:", predicted_word)

Next word prediction: blue
